const topicSeeds = {
  'load-balancer': ['Load Balancer', 'A traffic director that distributes requests across healthy compute targets.', 'Place it before stateless application instances; combine health checks, connection draining, and zone-aware routing.', ['Horizontal scaling', 'Failure isolation', 'TLS termination'], ['An additional network hop', 'Misconfiguration can create a shared failure point']],
  redis: ['Redis', 'An in-memory data structure store used for low-latency caches, counters, sessions, and coordination.', 'Use cache-aside with bounded TTLs and jitter. Keep durable truth elsewhere unless Redis persistence semantics explicitly fit.', ['Sub-millisecond operations', 'Rich atomic structures', 'Replication and clustering'], ['Memory cost', 'Hot keys and eviction surprises']],
  kafka: ['Kafka', 'A partitioned, replicated event log for durable, high-throughput asynchronous data movement.', 'Choose partition keys for ordering and balance; monitor consumer lag; make consumers idempotent.', ['Replayable events', 'High throughput', 'Decoupled producers and consumers'], ['Operational complexity', 'No global ordering across partitions']],
  'cap-theorem': ['CAP Theorem', 'During a network partition, a distributed system must choose between linearizable consistency and availability.', 'CAP applies under partitions. Describe the choice per operation—not once for an entire product.', ['Clarifies failure trade-offs', 'Improves data-store selection'], ['Frequently oversimplified', 'Does not capture latency or all consistency models']],
  'database-sharding': ['Database Sharding', 'Horizontal partitioning that places subsets of data on independent database nodes.', 'Select a stable, high-cardinality key and plan resharding, routing, and cross-shard query behavior.', ['Write scalability', 'Smaller indexes', 'Fault-domain isolation'], ['Cross-shard joins', 'Rebalancing and hot partitions']],
  replication: ['Replication', 'Maintaining multiple copies of data for availability, locality, and read scale.', 'Define leader election, replication lag tolerance, read consistency, and recovery point objectives.', ['High availability', 'Read scaling', 'Disaster recovery'], ['Lag and stale reads', 'Conflict handling']],
  microservices: ['Microservices', 'Independently deployable services aligned to clear business capabilities and data ownership.', 'Adopt only when team and scaling boundaries justify network, deployment, and observability overhead.', ['Independent scaling', 'Team autonomy', 'Fault isolation'], ['Distributed transactions', 'Operational overhead']],
  monolith: ['Monolith', 'A single deployable application whose modules execute in one process boundary.', 'A modular monolith is often the fastest reliable starting point; preserve boundaries so extraction remains possible.', ['Simple deployment', 'Local transactions', 'Easy debugging'], ['Coarse scaling', 'Growing deployment coordination']],
  'reverse-proxy': ['Reverse Proxy', 'A server-side intermediary that receives client traffic and forwards it to origin services.', 'Use it for TLS, routing, compression, policy, and controlled origin exposure.', ['Central traffic policy', 'Origin protection', 'Protocol handling'], ['Added hop', 'Configuration complexity']],
  caching: ['Caching', 'Storing reusable results closer to consumers to reduce latency and origin load.', 'Start with access patterns, define invalidation and staleness budgets, and prevent stampedes.', ['Lower latency', 'Reduced database load', 'Better resilience'], ['Stale data', 'Invalidation complexity']],
  'message-queue': ['Message Queue', 'A buffer that decouples producers from asynchronous consumers.', 'Specify delivery semantics, retry budgets, dead-letter handling, idempotency, and backpressure.', ['Load leveling', 'Failure decoupling', 'Async workflows'], ['Eventual consistency', 'Duplicate delivery']],
  cdn: ['CDN', 'A geographically distributed edge network that caches and serves content near users.', 'Use immutable asset versions, signed URLs where needed, and an origin shield.', ['Global latency reduction', 'Origin offload', 'DDoS absorption'], ['Cache invalidation', 'Egress and provider dependence']],
  'api-gateway': ['API Gateway', 'An edge entry point that routes APIs and applies cross-cutting policy.', 'Keep authentication, quotas, and routing at the edge while retaining domain authorization in services.', ['Unified policy', 'Routing and observability', 'Client simplification'], ['Shared dependency', 'Risk of business logic creep']],
};
const build = (slug, seed) => ({ slug, title: seed[0], summary: seed[1], explanation: seed[2], mentalModel: `Think of ${seed[0]} as one explicit boundary in a request or data path. Define what enters, what leaves, what state it owns, and how it fails.`, advantages: seed[3], disadvantages: seed[4], realWorldExamples: [`Large consumer platforms apply ${seed[0]} to isolate scale-sensitive paths.`, `Cloud-native teams combine ${seed[0]} with metrics, tracing, and automated recovery.`], interviewQuestions: [{ question: `When would you use ${seed[0]}?`, answer: `Use it when its latency, scale, ownership, or failure benefits exceed its operational cost.` }, { question: `What is the most important failure mode?`, answer: `Discuss overload, dependency failure, observability, safe retries, and a concrete mitigation.` }], animationSteps: [{ label: 'Request', description: 'A workload enters the architecture boundary.' }, { label: 'Decision', description: `${seed[0]} applies routing, storage, or delivery behavior.` }, { label: 'Result', description: 'The response or event continues with telemetry attached.' }], relatedTopics: Object.keys(topicSeeds).filter((key) => key !== slug).slice(0, 4) });
export const listTopics = () => Object.entries(topicSeeds).map(([slug, seed]) => ({ slug, title: seed[0], summary: seed[1] }));
export const getTopic = (slug) => topicSeeds[slug] ? build(slug, topicSeeds[slug]) : null;
