import QuizAttempt from '../models/QuizAttempt.js';
import { ApiError } from '../utils/ApiError.js';
import { recordActivity } from './activityService.js';

const questions = [
  { id: 'e-cache-aside', difficulty: 'Easy', type: 'mcq', topic: 'Caching', question: 'In cache-aside, what happens on a cache miss?', options: ['The client writes directly to cache only', 'The service reads the database and populates cache', 'The request is always rejected', 'The CDN elects a leader'], correctIndex: 1, explanation: 'The application loads the source of truth, returns it, and usually caches it with a bounded TTL.' },
  { id: 'e-lb-health', difficulty: 'Easy', type: 'scenario', topic: 'Load Balancing', question: 'One application instance is returning repeated 500 errors. What should remove it from rotation?', options: ['A database index', 'An active health check', 'A Kafka partition', 'A CDN purge'], correctIndex: 1, explanation: 'The load balancer uses health checks and connection draining to stop sending new traffic.' },
  { id: 'e-cdn', difficulty: 'Easy', type: 'architecture', topic: 'CDN', question: 'Which component should serve versioned images close to users worldwide?', options: ['Message broker', 'CDN', 'Primary database', 'Service registry'], correctIndex: 1, explanation: 'A CDN caches immutable objects at geographically distributed edge points.' },
  { id: 'e-replica', difficulty: 'Easy', type: 'mcq', topic: 'Replication', question: 'What is a common reason to add read replicas?', options: ['Guarantee zero stale reads', 'Scale read traffic', 'Remove every network partition', 'Replace backups'], correctIndex: 1, explanation: 'Read replicas increase read capacity, but replication lag must be considered.' },
  { id: 'm-hot-key', difficulty: 'Medium', type: 'scenario', topic: 'Partitioning', question: 'A celebrity post overloads one cache shard. Which problem is this?', options: ['Schema migration', 'Hot key skew', 'Clock drift only', 'Cold storage'], correctIndex: 1, explanation: 'A disproportionate amount of traffic targets one partition key; replication or key splitting can mitigate it.' },
  { id: 'm-idempotency', difficulty: 'Medium', type: 'scenario', topic: 'Reliability', question: 'A payment request times out and the client retries. What best prevents a double charge?', options: ['Longer JWT', 'Idempotency key', 'Read replica', 'Random partition'], correctIndex: 1, explanation: 'The server stores the outcome keyed by a unique idempotency token and returns it for retries.' },
  { id: 'm-kafka-order', difficulty: 'Medium', type: 'mcq', topic: 'Kafka', question: 'Where does Kafka preserve record ordering?', options: ['Across the entire cluster', 'Within a partition', 'Across unrelated topics', 'Only in the producer process'], correctIndex: 1, explanation: 'Ordering is guaranteed within a partition, which makes partition-key selection important.' },
  { id: 'm-cap', difficulty: 'Medium', type: 'mcq', topic: 'CAP Theorem', question: 'During a network partition, an AP operation prioritizes what?', options: ['Availability over linearizable consistency', 'Lower storage cost only', 'Global ordering', 'Synchronous backups'], correctIndex: 0, explanation: 'An AP design keeps responding and accepts that replicas may temporarily diverge.' },
  { id: 'h-feed-fanout', difficulty: 'Hard', type: 'scenario', topic: 'Feeds', question: 'Why might a feed system use fan-out-on-read for celebrity accounts?', options: ['To avoid writing one celebrity post into millions of follower inboxes', 'To guarantee no database reads', 'To remove ranking', 'To disable caching'], correctIndex: 0, explanation: 'Hybrid feed systems avoid enormous write amplification for high-fan-out publishers.' },
  { id: 'h-slo-burn', difficulty: 'Hard', type: 'mcq', topic: 'Observability', question: 'Why use multi-window SLO burn-rate alerts?', options: ['They detect both fast and sustained error-budget consumption', 'They eliminate incident response', 'They encrypt traces', 'They replace capacity tests'], correctIndex: 0, explanation: 'Fast and slow windows balance urgent detection against noisy transient spikes.' },
  { id: 'h-outbox', difficulty: 'Hard', type: 'architecture', topic: 'Consistency', question: 'A service must commit a database row and reliably publish an event. Which pattern avoids a dual-write gap?', options: ['Transactional outbox', 'Round-robin DNS', 'Cache warming', 'Client polling only'], correctIndex: 0, explanation: 'The row and outbox event commit in one local transaction; a relay publishes the event.' },
  { id: 'h-reshard', difficulty: 'Hard', type: 'scenario', topic: 'Sharding', question: 'Which shard-key property most reduces uneven partition load?', options: ['Low cardinality and monotonic values', 'High cardinality with workload-aware distribution', 'Human-readable names only', 'A constant value'], correctIndex: 1, explanation: 'A high-cardinality, well-distributed key avoids concentrating writes, though access locality also matters.' },
];
const publicQuestion = ({ correctIndex: _correctIndex, explanation: _explanation, ...question }) => question;
export const getQuiz = (difficulty = 'Medium', count = 5) => {
  const normalized = ['Easy', 'Medium', 'Hard'].includes(difficulty) ? difficulty : 'Medium';
  const pool = questions.filter((q) => q.difficulty === normalized).sort(() => Math.random() - 0.5);
  return { difficulty: normalized, questions: pool.slice(0, Math.min(Math.max(Number(count) || 4, 1), pool.length)).map(publicQuestion) };
};
export const submitQuiz = async (user, { difficulty = 'Medium', answers, durationSeconds = 0 }) => {
  const answerMap = new Map(answers.map((item) => [String(item.questionId), Number(item.selected)]));
  const selectedQuestions = questions.filter((question) => answerMap.has(question.id));
  if (!selectedQuestions.length) throw new ApiError(422, 'No recognized quiz questions were submitted');
  const graded = selectedQuestions.map((question) => ({ questionId: question.id, selected: answerMap.get(question.id), correct: answerMap.get(question.id) === question.correctIndex, correctIndex: question.correctIndex, explanation: question.explanation }));
  const score = graded.filter((item) => item.correct).length;
  const attempt = await QuizAttempt.create({ user, difficulty, answers: graded.map(({ questionId, selected, correct }) => ({ questionId, selected, correct })), score, total: graded.length, durationSeconds: Math.min(Math.max(Number(durationSeconds) || 0, 0), 86400) });
  await recordActivity(user, 'quiz', { label: `${difficulty} quiz`, metadata: { score, total: graded.length } });
  return { attemptId: attempt.id, score, total: graded.length, percentage: Math.round(score / graded.length * 100), results: graded };
};
export const getLeaderboard = async (limit = 10) => QuizAttempt.aggregate([{ $addFields: { percentage: { $multiply: [{ $divide: ['$score', '$total'] }, 100] } } }, { $sort: { percentage: -1, durationSeconds: 1, createdAt: 1 } }, { $limit: Math.min(Number(limit) || 10, 50) }, { $lookup: { from: 'users', localField: 'user', foreignField: '_id', as: 'user' } }, { $unwind: '$user' }, { $project: { score: 1, total: 1, percentage: { $round: ['$percentage', 0] }, difficulty: 1, durationSeconds: 1, createdAt: 1, 'user.name': 1, 'user.avatar': 1 } }]);
export const getUserAttempts = (user) => QuizAttempt.find({ user }).sort({ createdAt: -1 }).limit(20).lean();
