import { Router } from 'express';
import rateLimit from 'express-rate-limit';
import * as controller from '../controllers/designController.js';
import protect from '../middleware/auth.js';
import validate from '../middleware/validate.js';
import asyncHandler from '../utils/asyncHandler.js';
import { designValidator, saveDesignValidator } from '../utils/validators.js';
const router = Router();
const aiLimit = rateLimit({ windowMs: 60 * 60 * 1000, limit: 30, standardHeaders: 'draft-7', legacyHeaders: false, message: { success: false, message: 'AI generation limit reached. Try again later.' } });
router.get('/shared/:shareId', asyncHandler(controller.shared));
router.use(protect);
router.post('/generate', aiLimit, validate(designValidator), asyncHandler(controller.generate));
router.post('/', validate(saveDesignValidator), asyncHandler(controller.save));
router.get('/', asyncHandler(controller.list));
router.get('/:id', asyncHandler(controller.getOne));
router.patch('/:id', asyncHandler(controller.update));
router.delete('/:id', asyncHandler(controller.remove));
router.post('/:id/duplicate', asyncHandler(controller.duplicate));
router.patch('/:id/favourite', asyncHandler(controller.favourite));
router.post('/:id/share', asyncHandler(controller.share));
export default router;
