import { Router } from 'express';
import * as controller from '../controllers/quizController.js';
import protect from '../middleware/auth.js';
import validate from '../middleware/validate.js';
import asyncHandler from '../utils/asyncHandler.js';
import { quizSubmitValidator } from '../utils/validators.js';
const router = Router();
router.use(protect);
router.get('/', asyncHandler(controller.getQuiz));
router.post('/submit', validate(quizSubmitValidator), asyncHandler(controller.submit));
router.get('/leaderboard', asyncHandler(controller.leaderboard));
router.get('/attempts', asyncHandler(controller.attempts));
export default router;
