const node = (id, label, kind, x, y, technology, description) => ({ id, type: 'architecture', position: { x, y }, data: { label, kind, technology, description, detailsKey: technology.toLowerCase().replace(/[^a-z0-9]+/g, '-') } });
const edge = (source, target, label) => ({ id: `e-${source}-${target}`, source, target, label, type: 'smoothstep', animated: true });

export const buildFallbackArchitecture = (input) => {
  const name = input.systemName;
  const scale = input.expectedUsers;
  const featureSet = new Set(input.features || []);
  return {
    overview: `${name} uses a multi-region, API-first ${input.architectureType.toLowerCase()} architecture sized for ${scale} users. Stateless compute, asynchronous workflows, and independently scalable data paths protect latency during traffic spikes.`,
    functionalRequirements: input.features.map((feature) => `Users can access ${feature.toLowerCase()} capabilities with consistent cross-device state.`),
    nonFunctionalRequirements: ['99.95% API availability with graceful degradation', 'p95 read latency below 200 ms and write latency below 400 ms', 'Horizontal scalability without service interruption', 'Durable, encrypted data with tested recovery objectives', 'Observable request paths and auditable security events'],
    databaseDesign: [
      { name: 'Primary operational store', type: 'PostgreSQL', purpose: 'Strongly consistent users, relationships, and transactions', schema: ['users(id, email, profile, created_at)', 'entities(id, owner_id, payload, version)', 'relationships(source_id, target_id, state)'] },
      { name: 'High-volume document store', type: 'MongoDB', purpose: 'Flexible content and denormalized read models', schema: ['content(_id, author_id, body, counters, created_at)', 'feeds(user_id, ranked_items, generated_at)'] },
      { name: 'Search index', type: 'Elasticsearch', purpose: 'Full-text search and faceted discovery', schema: ['content_v1: text, author, tags, popularity, timestamp'] },
    ],
    apiEndpoints: [
      { method: 'POST', path: '/v1/auth/sessions', purpose: 'Create an authenticated session' },
      { method: 'GET', path: '/v1/feed?cursor={cursor}', purpose: 'Return a cursor-paginated personalized feed' },
      { method: 'POST', path: '/v1/content', purpose: 'Create content using an idempotency key' },
      { method: 'GET', path: '/v1/content/{id}', purpose: 'Fetch content and viewer-specific state' },
      { method: 'POST', path: '/v1/events', purpose: 'Accept batched engagement events' },
    ],
    microservices: [
      { name: 'Identity Service', responsibility: 'Accounts, sessions, authorization, and risk signals', technology: 'Node.js + PostgreSQL' },
      { name: 'Content Service', responsibility: 'Content lifecycle and metadata', technology: 'Node.js + MongoDB' },
      { name: 'Feed Service', responsibility: 'Candidate generation, ranking, and pagination', technology: 'Node.js + Redis' },
      { name: 'Notification Worker', responsibility: 'Fan-out and multi-channel delivery', technology: 'Kafka consumer' },
      ...(featureSet.has('Payment') ? [{ name: 'Payment Service', responsibility: 'Idempotent payment orchestration and ledgering', technology: 'Node.js + PostgreSQL' }] : []),
    ],
    authenticationFlow: ['Client submits credentials over TLS', 'Identity service verifies the bcrypt hash and risk policy', 'Short-lived signed access token and rotated refresh token are issued', 'API Gateway validates signature, issuer, audience, and expiry', 'Fine-grained authorization is enforced again by the owning service'],
    scalingStrategy: ['Keep API instances stateless behind regional load balancers', 'Autoscale compute on request rate, p95 latency, and queue lag', 'Partition asynchronous consumers by stable entity key', 'Use multi-region active-passive writes initially; evolve hot paths selectively'],
    cachingStrategy: ['Cache hot read models in Redis with TTL jitter', 'Use cache-aside for reads and invalidate after committed writes', 'Protect origins with request coalescing and stale-while-revalidate', 'Never treat cache as the source of truth'],
    loadBalancer: { choice: 'Managed L7 load balancer + Nginx ingress', strategy: 'Least outstanding requests with health-aware routing', reason: 'TLS termination, WAF integration, canaries, and regional failover' },
    redisUsage: ['Session and token revocation metadata', 'Feed/page cache', 'Distributed rate-limit counters', 'Short-lived idempotency responses'],
    kafkaUsage: ['Durable engagement event stream', 'Notification and search-index fan-out', 'Analytics ingestion decoupled from request latency', 'Replayable integration log with schema versioning'],
    cdn: ['Cache versioned media near users', 'Signed URLs protect private assets', 'Origin shield reduces storage egress and stampedes'],
    databaseSharding: ['Start with indexed primary/replicas; shard only measured hot tables', 'Shard user-scoped data by hashed user ID', 'Maintain a shard directory and avoid cross-shard transactions'],
    replication: ['Synchronous multi-AZ primary replication for durability', 'Asynchronous read replicas for feeds and analytics', 'Cross-region replica with tested promotion runbook'],
    security: ['TLS 1.3 in transit and managed-key encryption at rest', 'WAF, least-privilege service identities, and secret rotation', 'Parameterized queries, schema validation, malware scanning for uploads', 'Immutable audit events and dependency/container scanning'],
    rateLimiting: ['Token bucket by account and IP at the gateway', 'Endpoint-specific quotas with Retry-After', 'Stricter anonymous and authentication limits'],
    monitoring: ['RED metrics for every service', 'Distributed traces with propagated correlation IDs', 'SLO burn-rate alerts instead of raw threshold noise', 'Synthetic regional probes and dependency dashboards'],
    logging: ['Structured JSON with request, user, and trace IDs', 'Centralized searchable logs with PII redaction', 'Separate immutable audit stream with retention policy'],
    estimatedMonthlyCost: { currency: 'USD', low: scale.includes('100 Million') ? 180000 : 12000, high: scale.includes('100 Million') ? 420000 : 38000, breakdown: [{ item: 'Compute and orchestration', cost: '35%' }, { item: 'Databases and cache', cost: '30%' }, { item: 'CDN, storage, and egress', cost: '25%' }, { item: 'Observability and security', cost: '10%' }], assumptions: [`${scale} registered users`, `${input.traffic} traffic profile`, 'Managed cloud services with reserved baseline capacity'] },
    tradeOffs: [{ decision: 'Asynchronous fan-out', benefit: 'Low request latency and independent scaling', cost: 'Eventual consistency and operational complexity' }, { decision: 'Polyglot persistence', benefit: 'Storage optimized per access pattern', cost: 'More migrations, skills, and failure modes' }, { decision: 'Denormalized read models', benefit: 'Predictable high-throughput reads', cost: 'Reconciliation and stale-data handling' }],
    bottlenecks: [{ risk: 'Hot users or viral content', impact: 'Skewed partitions and cache pressure', mitigation: 'Key salting, adaptive replication, and admission control' }, { risk: 'Consumer lag', impact: 'Stale feeds, search, and notifications', mitigation: 'Lag-based autoscaling, DLQ, backpressure, and replay tooling' }, { risk: 'Database connection exhaustion', impact: 'Cascading timeouts', mitigation: 'Pool budgets, proxying, load shedding, and bounded retries' }],
    futureImprovements: ['Introduce cell-based architecture to reduce blast radius', 'Add multi-region active-active reads and selective writes', 'Train ranking models from privacy-safe event features', 'Automate game days and recovery verification'],
    bestPractices: ['Use idempotency keys on retryable writes', 'Version events and APIs compatibly', 'Set explicit timeout, retry, and circuit-breaker budgets', 'Document data ownership and deletion workflows', 'Capacity-test the complete critical path'],
    diagram: {
      nodes: [node('users', 'Web & Mobile Users', 'client', 0, 180, 'Client', 'End-user applications'), node('cdn', 'Edge CDN + WAF', 'cdn', 220, 40, 'CDN', 'Edge caching and threat filtering'), node('gateway', 'API Gateway', 'gateway', 220, 220, 'Nginx', 'Routing, auth, and throttling'), node('identity', 'Identity Service', 'service', 480, 40, 'Node.js', 'Authentication and authorization'), node('content', 'Content Service', 'service', 480, 160, 'Node.js', 'Core domain writes and reads'), node('feed', 'Feed Service', 'service', 480, 280, 'Node.js', 'Personalized read assembly'), node('workers', 'Async Workers', 'service', 480, 400, 'Kubernetes', 'Notifications, indexing, and media jobs'), node('redis', 'Redis Cache', 'cache', 740, 40, 'Redis', 'Hot data, sessions, and counters'), node('kafka', 'Event Backbone', 'queue', 740, 160, 'Kafka', 'Durable asynchronous events'), node('database', 'Operational Data', 'database', 740, 280, 'PostgreSQL', 'Authoritative relational data'), node('storage', 'Object Storage', 'storage', 740, 400, 'S3', 'Original and transformed media'), node('observe', 'Observability', 'observability', 1000, 220, 'OpenTelemetry', 'Metrics, logs, and traces')],
      edges: [edge('users', 'cdn', 'media'), edge('users', 'gateway', 'HTTPS'), edge('gateway', 'identity', 'auth'), edge('gateway', 'content', 'API'), edge('gateway', 'feed', 'API'), edge('identity', 'redis', 'sessions'), edge('identity', 'database', 'accounts'), edge('content', 'database', 'transactions'), edge('content', 'storage', 'media'), edge('content', 'kafka', 'events'), edge('feed', 'redis', 'cache'), edge('kafka', 'workers', 'consume'), edge('workers', 'storage', 'transform'), edge('gateway', 'observe', 'telemetry')],
    },
  };
};

const side = (name, videoFirst) => ({ name, architecture: videoFirst ? 'Event-driven media pipeline with independently scaled recommendation and delivery planes' : 'Service-oriented social graph with fan-out feed pipelines', database: ['Sharded relational metadata', 'Wide-column/document read models'], caching: ['Redis hot-object and session cache', 'Edge metadata caching'], storage: ['Multi-region object storage', 'Tiered media lifecycle'], scaling: ['Stateless services', 'Key-based partitioning and cells'], messageQueue: ['Kafka event backbone', 'At-least-once consumers'], cdn: ['Multi-CDN media delivery', 'Signed URLs and origin shielding'], security: ['TLS, WAF, abuse detection', 'Least privilege and audit trails'], pros: videoFirst ? ['Optimized media delivery', 'Strong recommendation feedback loop'] : ['Rich relationship model', 'Flexible content graph'], cons: videoFirst ? ['High storage and egress cost', 'Complex transcoding'] : ['Celebrity fan-out hotspots', 'Graph consistency complexity'] });
export const buildFallbackComparison = ({ systemA, systemB }) => ({ summary: `Both ${systemA} and ${systemB} require globally distributed delivery, but their dominant access patterns drive different data and ranking priorities.`, systems: { left: side(systemA, false), right: side(systemB, true) }, keyDifferences: [{ dimension: 'Primary workload', [systemA]: 'Social graph and feed fan-out', [systemB]: 'Media delivery and watch-time ranking', verdict: 'Model the dominant read path first' }, { dimension: 'Cost center', [systemA]: 'Feed computation and graph storage', [systemB]: 'Encoding, storage, and CDN egress', verdict: 'FinOps follows workload shape' }], interviewTakeaways: ['State assumptions before selecting technology', 'Separate control, data, and asynchronous planes', 'Discuss skew, failure, consistency, and cost—not only happy-path scale'] });
