import { AnimatePresence, motion } from 'framer-motion';
import { Bell, Search } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Outlet, useLocation } from 'react-router-dom';
import Brand from '../components/Brand';
import CommandPalette from '../components/navigation/CommandPalette';
import MobileNav from '../components/navigation/MobileNav';
import Sidebar from '../components/navigation/Sidebar';
import { useAuth } from '../context/AuthContext';
export default function AppLayout() { const [palette, setPalette] = useState(false); const { user } = useAuth(); const location = useLocation(); useEffect(() => { const handler = (event) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setPalette((value) => !value); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, []); return <div className="min-h-screen bg-canvas text-ink lg:grid lg:grid-cols-[256px_1fr]"><Sidebar /><div className="min-w-0"><header className="sticky top-0 z-30 flex h-16 items-center gap-3 border-b border-white/10 bg-canvas/80 px-5 backdrop-blur-xl lg:px-8"><div className="lg:hidden"><Brand compact /></div><button onClick={() => setPalette(true)} className="ml-auto hidden w-64 items-center gap-2 rounded-xl border border-white/10 bg-white/[.03] px-3 py-2 text-left text-xs text-slate-500 sm:flex"><Search size={15} />Search or jump to...<kbd className="ml-auto rounded border border-white/10 px-1.5 py-0.5">⌘K</kbd></button><button className="rounded-xl p-2 text-slate-500 hover:bg-white/5 hover:text-white" aria-label="Notifications"><Bell size={18} /></button><div className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-cyan-300 to-violet-400 text-sm font-bold text-slate-950" title={user?.name}>{user?.name?.[0]?.toUpperCase() || 'A'}</div></header><AnimatePresence mode="wait"><motion.main key={location.pathname} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -5 }} transition={{ duration: .2 }} className="mx-auto max-w-[1600px] p-5 pb-28 lg:p-8 lg:pb-10"><Outlet /></motion.main></AnimatePresence></div><MobileNav /><CommandPalette open={palette} onClose={() => setPalette(false)} /></div>; }
