import { ArrowRight, Clock3, FolderHeart, Search, Sparkles } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { activityApi } from '../api/activityApi';
import { designApi } from '../api/designApi';
import Button from '../components/common/Button';
import { CardSkeleton } from '../components/common/Skeleton';
import DesignCard from '../components/design/DesignCard';
import { useAuth } from '../context/AuthContext';
export default function DashboardPage() { const { user } = useAuth(); const [designs, setDesigns] = useState([]); const [total, setTotal] = useState(0); const [activity, setActivity] = useState([]); const [loading, setLoading] = useState(true); const load = useCallback(async () => { setLoading(true); try { const [list, history] = await Promise.all([designApi.list({ limit: 6 }), activityApi.list({ limit: 5 })]); setDesigns(list.items); setTotal(list.meta?.total || list.items.length); setActivity(history); } catch { setDesigns([]); } finally { setLoading(false); } }, []); useEffect(() => { load(); }, [load]); return <div><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm text-cyan-300">Architecture command center</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Welcome, {user?.name?.split(' ')[0] || 'Architect'}.</h1><p className="mt-2 text-slate-400">What resilient system will you explore today?</p></div><Link to="/app/new"><Button><Sparkles size={17} />New design</Button></Link></div><div className="mt-8 grid gap-4 sm:grid-cols-3"><Stat icon={FolderHeart} label="Saved architectures" value={total} /><Stat icon={Clock3} label="Recent activities" value={activity.length} /><Stat icon={Sparkles} label="AI credits" value={user?.aiCredits ?? '—'} /></div><Link to="/app/designs" className="glass mt-8 flex items-center gap-3 rounded-2xl p-4 text-slate-500 transition hover:border-cyan-300/20 hover:text-slate-300"><Search size={18} /><span className="text-sm">Search your architectures...</span><span className="ml-auto text-xs">Open library <ArrowRight size={13} className="ml-1 inline" /></span></Link><section className="mt-8"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Recent designs</h2><Link to="/app/designs" className="text-sm text-cyan-300">View all</Link></div><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{loading ? Array.from({ length: 3 }, (_, index) => <CardSkeleton key={index} />) : designs.length ? designs.map((design) => <DesignCard key={design._id} design={design} />) : <div className="glass col-span-full rounded-2xl p-8 text-center text-sm text-slate-500">No designs yet. Generate your first production architecture.</div>}</div></section>{activity.length > 0 && <section className="mt-10"><h2 className="text-lg font-semibold">Recently viewed</h2><div className="mt-4 divide-y divide-white/[.06] rounded-2xl border border-white/10 bg-white/[.02]">{activity.map((item) => <div key={item._id} className="flex items-center gap-3 px-4 py-3 text-sm"><Clock3 size={15} className="text-slate-600" /><span className="text-slate-300">{item.label || item.type}</span><span className="ml-auto text-xs text-slate-600">{new Date(item.createdAt).toLocaleDateString()}</span></div>)}</div></section>}</div>; }
function Stat({ icon: Icon, label, value }) { return <div className="glass rounded-2xl p-5"><Icon className="text-cyan-300" size={19} /><p className="mt-5 text-2xl font-semibold">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div>; }
