import { Plus, Search } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { Link } from 'react-router-dom';
import { designApi } from '../api/designApi';
import Button from '../components/common/Button';
import EmptyState from '../components/common/EmptyState';
import PageHeader from '../components/common/PageHeader';
import { CardSkeleton } from '../components/common/Skeleton';
import DesignCard from '../components/design/DesignCard';
import useDebounce from '../hooks/useDebounce';
export default function DesignsPage() { const [items, setItems] = useState([]); const [search, setSearch] = useState(''); const [favourite, setFavourite] = useState(false); const [loading, setLoading] = useState(true); const debounced = useDebounce(search); const load = useCallback(async () => { setLoading(true); try { const data = await designApi.list({ search: debounced, favourite, limit: 50 }); setItems(data.items); } catch (error) { toast.error(error.response?.data?.message || 'Unable to load designs'); } finally { setLoading(false); } }, [debounced, favourite]); useEffect(() => { load(); }, [load]); const toggle = async (design) => { try { await designApi.favourite(design._id, !design.isFavourite); setItems((current) => current.map((item) => item._id === design._id ? { ...item, isFavourite: !item.isFavourite } : item)); } catch { toast.error('Could not update favourite'); } }; const duplicate = async (design) => { try { await designApi.duplicate(design._id); toast.success('Design duplicated'); load(); } catch { toast.error('Could not duplicate design'); } }; const remove = async (design) => { if (!window.confirm(`Delete “${design.name}”? This cannot be undone.`)) return; try { await designApi.remove(design._id); setItems((current) => current.filter((item) => item._id !== design._id)); toast.success('Design deleted'); } catch { toast.error('Could not delete design'); } }; return <div><PageHeader title="Saved designs" description="Search, study, favourite, duplicate, and manage your architecture library." actions={<Link to="/app/new"><Button><Plus size={16} />New design</Button></Link>} /><div className="mt-8 flex flex-col gap-3 sm:flex-row"><label className="flex flex-1 items-center gap-3 rounded-xl border border-white/10 bg-white/[.025] px-4"><Search size={17} className="text-slate-600" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search architecture names..." className="h-12 w-full bg-transparent text-sm outline-none placeholder:text-slate-700" /></label><button onClick={() => setFavourite(!favourite)} className={`rounded-xl border px-4 text-sm transition ${favourite ? 'border-amber-300/25 bg-amber-300/10 text-amber-200' : 'border-white/10 text-slate-400 hover:bg-white/5'}`}>★ Favourites</button></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{loading ? Array.from({ length: 6 }, (_, index) => <CardSkeleton key={index} />) : items.map((design) => <DesignCard key={design._id} design={design} onFavourite={toggle} onDuplicate={duplicate} onDelete={remove} />)}</div>{!loading && !items.length && <div className="mt-6"><EmptyState title="No matching architectures" description="Generate a new system or clear your search filters." action={<Link to="/app/new"><Button>Start designing</Button></Link>} /></div>}</div>; }
