import { BrainCircuit, Database, Network, ShieldCheck } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { designApi } from '../api/designApi';
import PageHeader from '../components/common/PageHeader';
import DesignForm from '../components/design/DesignForm';
import { TEMPLATES } from '../utils/constants';
const stages = ['Analyzing traffic patterns', 'Selecting data stores', 'Designing service boundaries', 'Modeling failure modes', 'Building architecture graph'];
export default function NewDesignPage() { const [loading, setLoading] = useState(false); const [stage, setStage] = useState(0); const navigate = useNavigate(); const [params] = useSearchParams(); const preset = useMemo(() => TEMPLATES.find((item) => item.name === params.get('template')), [params]); useEffect(() => { if (!loading) return undefined; const timer = setInterval(() => setStage((value) => Math.min(value + 1, stages.length - 1)), 1300); return () => clearInterval(timer); }, [loading]); const submit = async (input) => { setLoading(true); setStage(0); try { const result = await designApi.generate(input); toast.success(result.generation.provider === 'fallback' ? 'Architecture generated with offline engine' : 'AI architecture generated'); navigate(`/app/designs/${result.design._id}`); } catch (error) { toast.error(error.response?.data?.message || 'Generation failed. Please retry.'); setLoading(false); } }; return <div><PageHeader eyebrow="AI architecture studio" title="Create a new system design" description="Describe scale and product capabilities. The architecture engine will generate a complete, editable production plan." /><div className="mt-8 grid gap-6 xl:grid-cols-[1fr_330px]"><div className="glass rounded-3xl p-5 sm:p-7"><DesignForm key={preset?.name || 'default'} preset={preset} onSubmit={submit} loading={loading} /></div><aside className="space-y-4"><Info icon={BrainCircuit} title="Requirement synthesis" text="Translates product needs into measurable functional and non-functional requirements." /><Info icon={Network} title="Architecture topology" text="Builds draggable services, data stores, queues, caches, edge, and observability nodes." /><Info icon={Database} title="Data & scale" text="Models schema, partitioning, replication, cache, consistency, and capacity trade-offs." /><Info icon={ShieldCheck} title="Production review" text="Surfaces security, cost, bottlenecks, monitoring, and future evolution." /></aside></div>{loading && <div className="fixed inset-0 z-[90] grid place-items-center bg-[#07080c]/85 px-5 backdrop-blur-xl"><div className="w-full max-w-lg text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl border border-cyan-300/20 bg-cyan-300/10 text-cyan-300 shadow-glow"><BrainCircuit className="animate-pulse" size={30} /></div><h2 className="mt-6 text-2xl font-semibold">Architecting your system</h2><p className="mt-2 font-mono text-sm text-cyan-300">{stages[stage]}<span className="animate-pulse">_</span></p><div className="mt-7 h-1 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-gradient-to-r from-cyan-300 to-violet-400 transition-all duration-700" style={{ width: `${((stage + 1) / stages.length) * 100}%` }} /></div><p className="mt-4 text-xs text-slate-600">This can take up to 40 seconds.</p></div></div>}</div>; }
function Info({ icon: Icon, title, text }) { return <div className="rounded-2xl border border-white/[.07] bg-white/[.02] p-5"><Icon size={19} className="text-violet-300" /><h3 className="mt-4 text-sm font-medium text-white">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></div>; }
