import { Mail, Save, Sparkles, UserRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { authApi } from '../api/authApi';
import Button from '../components/common/Button';
import PageHeader from '../components/common/PageHeader';
import { useAuth } from '../context/AuthContext';
export default function ProfilePage() { const { user, updateUser } = useAuth(); const [form, setForm] = useState({ name: '', bio: '', avatar: '' }); const [saving, setSaving] = useState(false); useEffect(() => { if (user) setForm({ name: user.name || '', bio: user.bio || '', avatar: user.avatar || '' }); }, [user]); const save = async (event) => { event.preventDefault(); setSaving(true); try { const data = await authApi.updateProfile(form); updateUser(data.user); toast.success('Profile updated'); } catch (error) { toast.error(error.response?.data?.message || 'Could not update profile'); } finally { setSaving(false); } }; return <div><PageHeader title="Profile" description="Manage the identity attached to your architecture work." /><div className="mt-8 grid gap-6 lg:grid-cols-[320px_1fr]"><aside className="glass h-fit rounded-3xl p-6 text-center"><div className="mx-auto grid h-24 w-24 place-items-center overflow-hidden rounded-3xl bg-gradient-to-br from-cyan-300 to-violet-400 text-3xl font-bold text-slate-950">{form.avatar ? <img src={form.avatar} alt="" className="h-full w-full object-cover" /> : user?.name?.[0]}</div><h2 className="mt-5 text-xl font-semibold">{user?.name}</h2><p className="mt-1 flex items-center justify-center gap-2 text-sm text-slate-500"><Mail size={14} />{user?.email}</p><div className="mt-6 grid grid-cols-2 gap-2"><Stat value={user?.aiCredits ?? '—'} label="AI credits" /><Stat value="Dev" label="Role" /></div></aside><form onSubmit={save} className="glass rounded-3xl p-6 sm:p-8"><h2 className="flex items-center gap-2 font-semibold"><UserRound size={18} className="text-cyan-300" />Personal information</h2><div className="mt-6 space-y-5"><Field label="Display name" value={form.name} onChange={(name) => setForm({ ...form, name })} /><Field label="Avatar URL" value={form.avatar} onChange={(avatar) => setForm({ ...form, avatar })} placeholder="https://..." /><label className="block text-sm text-slate-400">Bio<textarea value={form.bio} maxLength={280} rows={5} onChange={(event) => setForm({ ...form, bio: event.target.value })} className="mt-2 w-full resize-none rounded-xl border border-white/10 bg-black/20 p-4 text-white" /><span className="mt-1 block text-right text-xs text-slate-700">{form.bio.length}/280</span></label></div><Button type="submit" loading={saving} className="mt-6"><Save size={16} />Save profile</Button><div className="mt-8 rounded-2xl border border-violet-300/10 bg-violet-300/5 p-4"><p className="flex items-center gap-2 text-sm text-violet-200"><Sparkles size={15} />Your profile name appears on unlisted shared designs.</p></div></form></div></div>; }
function Field({ label, value, onChange, ...props }) { return <label className="block text-sm text-slate-400">{label}<input {...props} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-white" /></label>; }
function Stat({ value, label }) { return <div className="rounded-xl bg-white/[.04] p-3"><p className="font-semibold text-white">{value}</p><p className="mt-1 text-[10px] text-slate-600">{label}</p></div>; }
