import { LogOut, Save, SlidersHorizontal } from 'lucide-react';
import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { useNavigate } from 'react-router-dom';
import { authApi } from '../api/authApi';
import Button from '../components/common/Button';
import PageHeader from '../components/common/PageHeader';
import { useAuth } from '../context/AuthContext';
import { ARCHITECTURES } from '../utils/constants';
export default function SettingsPage() { const { user, updateUser, logout } = useAuth(); const navigate = useNavigate(); const [preferences, setPreferences] = useState({ reducedMotion: false, emailUpdates: true, defaultArchitecture: 'Microservices' }); const [saving, setSaving] = useState(false); useEffect(() => { if (user?.preferences) setPreferences(user.preferences); }, [user]); const save = async () => { setSaving(true); try { const data = await authApi.updateProfile({ preferences }); updateUser(data.user); toast.success('Preferences saved'); } catch (error) { toast.error(error.response?.data?.message || 'Could not save settings'); } finally { setSaving(false); } }; const signOut = async () => { await logout(); navigate('/'); }; return <div><PageHeader title="Settings" description="Tune your workspace and default design behavior." /><div className="mt-8 max-w-3xl space-y-5"><section className="glass rounded-3xl p-6"><h2 className="flex items-center gap-2 font-semibold"><SlidersHorizontal size={18} className="text-cyan-300" />Workspace preferences</h2><div className="mt-6 space-y-6"><Toggle label="Reduce motion" description="Minimize decorative transitions and canvas animation." checked={preferences.reducedMotion} onChange={(value) => setPreferences({ ...preferences, reducedMotion: value })} /><Toggle label="Product updates" description="Receive occasional release and learning updates." checked={preferences.emailUpdates} onChange={(value) => setPreferences({ ...preferences, emailUpdates: value })} /><label className="block text-sm text-slate-300">Default architecture<select value={preferences.defaultArchitecture} onChange={(event) => setPreferences({ ...preferences, defaultArchitecture: event.target.value })} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0b0f18] px-4 py-3">{ARCHITECTURES.map((item) => <option key={item}>{item}</option>)}</select></label></div><Button onClick={save} loading={saving} className="mt-7"><Save size={16} />Save preferences</Button></section><section className="rounded-3xl border border-red-300/10 bg-red-300/[.025] p-6"><h2 className="font-semibold text-red-200">Session</h2><p className="mt-2 text-sm text-slate-500">Signing out revokes the current JWT generation on the server.</p><Button variant="danger" onClick={signOut} className="mt-5"><LogOut size={16} />Sign out</Button></section></div></div>; }
function Toggle({ label, description, checked, onChange }) { return <label className="flex cursor-pointer items-center justify-between gap-5"><span><span className="block text-sm text-slate-300">{label}</span><span className="mt-1 block text-xs text-slate-600">{description}</span></span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="peer sr-only" /><span className="relative h-6 w-11 rounded-full bg-slate-800 transition peer-checked:bg-cyan-400/70 after:absolute after:left-1 after:top-1 after:h-4 after:w-4 after:rounded-full after:bg-white after:transition peer-checked:after:translate-x-5" /></label>; }
