export const nodeDetails = {
  redis: { title: 'Redis', what: 'An in-memory data structure server for caches, counters, sessions, and coordination.', why: 'It removes repeated work from databases and serves latency-sensitive state.', advantages: ['Sub-millisecond operations', 'Atomic rich data structures', 'Replication and clustering'], disadvantages: ['Memory is expensive', 'Hot keys and eviction require care'], alternatives: ['Memcached', 'Dragonfly', 'Database-native caches'], companies: ['GitHub', 'Uber', 'X'] },
  kafka: { title: 'Apache Kafka', what: 'A replicated, partitioned event log.', why: 'It decouples high-throughput producers and consumers with replay.', advantages: ['Durable replay', 'High throughput', 'Ordered partitions'], disadvantages: ['Operational complexity', 'Partition planning matters'], alternatives: ['Pulsar', 'Kinesis', 'NATS JetStream'], companies: ['LinkedIn', 'Netflix', 'Uber'] },
  rabbitmq: { title: 'RabbitMQ', what: 'A general-purpose message broker with flexible routing.', why: 'It suits work queues and complex routing at moderate throughput.', advantages: ['Rich routing', 'Mature acknowledgements', 'Easy work queues'], disadvantages: ['Lower log-style throughput', 'Queue tuning'], alternatives: ['Kafka', 'SQS', 'NATS'], companies: ['Reddit', 'Robinhood', 'Mozilla'] },
  mongodb: { title: 'MongoDB', what: 'A document database storing BSON records.', why: 'Flexible nested models and scalable document-centric access.', advantages: ['Flexible schema', 'Natural object mapping', 'Sharding'], disadvantages: ['Denormalization trade-offs', 'Cross-document design care'], alternatives: ['PostgreSQL JSONB', 'DynamoDB', 'Couchbase'], companies: ['Adobe', 'Coinbase', 'eBay'] },
  postgresql: { title: 'PostgreSQL', what: 'A mature relational database with strong transactions.', why: 'It is a dependable system of record for relational and transactional data.', advantages: ['ACID guarantees', 'Powerful indexing and SQL', 'Extensible'], disadvantages: ['Write scaling needs planning', 'Schema migrations'], alternatives: ['MySQL', 'CockroachDB', 'Aurora'], companies: ['Instagram', 'Reddit', 'Spotify'] },
  elasticsearch: { title: 'Elasticsearch', what: 'A distributed inverted-index search and analytics engine.', why: 'It provides full-text relevance, filtering, and aggregations.', advantages: ['Fast full-text search', 'Aggregations', 'Horizontal scale'], disadvantages: ['Memory intensive', 'Not the primary truth store'], alternatives: ['OpenSearch', 'Typesense', 'Meilisearch'], companies: ['GitHub', 'Stack Overflow', 'Shopify'] },
  cdn: { title: 'Content Delivery Network', what: 'A global edge network that caches content close to users.', why: 'It lowers latency, origin load, and exposure to traffic attacks.', advantages: ['Global performance', 'Origin offload', 'DDoS absorption'], disadvantages: ['Invalidation complexity', 'Egress cost'], alternatives: ['Regional edge compute', 'Self-hosted PoPs'], companies: ['Netflix', 'Amazon', 'Discord'] },
  nginx: { title: 'Nginx', what: 'A high-performance reverse proxy and web server.', why: 'It handles TLS, routing, buffering, and load balancing at the edge.', advantages: ['Efficient connections', 'Mature configuration', 'Broad protocol support'], disadvantages: ['Configuration complexity', 'Stateful reload discipline'], alternatives: ['Envoy', 'HAProxy', 'Traefik'], companies: ['Dropbox', 'Airbnb', 'Netflix'] },
  'api-gateway': { title: 'API Gateway', what: 'A managed or self-hosted entry point for APIs.', why: 'It centralizes routing, authentication checks, quotas, and telemetry.', advantages: ['Unified policy', 'Client simplification', 'Traffic control'], disadvantages: ['Shared dependency', 'Can become bloated'], alternatives: ['Nginx', 'Envoy', 'Kong'], companies: ['Amazon', 'Netflix', 'SoundCloud'] },
  docker: { title: 'Docker', what: 'A standard runtime and image format for containers.', why: 'It packages applications with reproducible dependencies.', advantages: ['Portability', 'Fast deployment', 'Isolation'], disadvantages: ['Image security', 'Stateful workload complexity'], alternatives: ['Podman', 'containerd', 'Firecracker'], companies: ['PayPal', 'Spotify', 'Shopify'] },
  kubernetes: { title: 'Kubernetes', what: 'A declarative container orchestration platform.', why: 'It schedules, scales, updates, and recovers container workloads.', advantages: ['Self-healing', 'Autoscaling', 'Deployment primitives'], disadvantages: ['Steep operational curve', 'Platform overhead'], alternatives: ['ECS', 'Nomad', 'Cloud Run'], companies: ['Spotify', 'Pinterest', 'OpenAI'] },
};
export const resolveNodeDetails = (data = {}) => { const key = String(data.detailsKey || data.technology || data.label || '').toLowerCase(); return nodeDetails[key] || Object.entries(nodeDetails).find(([name]) => key.includes(name))?.[1] || { title: data.label || 'Architecture component', what: data.description || 'A component in this distributed system.', why: 'It owns a clear responsibility in the request or data path.', advantages: ['Independent responsibility', 'Observable boundary'], disadvantages: ['Adds operational surface area'], alternatives: ['Consolidate with an adjacent component'], companies: ['Common across large-scale platforms'] }; };
